import { createFileRoute, Link } from "@tanstack/react-router";

import { PageHero } from "@/components/marketing";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/_marketing/privacy")({
  head: () =>
    pageHead({
      path: "/privacy",
      title: "Privacy — MarginMap",
      description:
        "What MarginMap collects, where it is stored, how long it is kept, and how to request access or deletion of your workspace data.",
    }),
  component: PrivacyPage,
});

const SECTIONS: { heading: string; body: string[] }[] = [
  {
    heading: "What we collect",
    body: [
      "Account data: the email address you sign in with, or the identifier returned by Google or Apple if you use social sign-in. Passwords, when used, are handled by the authentication provider and are never stored by the application.",
      "Profile data you enter: display name, country, preferred currency and default role mode.",
      "Workspace data you create: searches, watchlists, deal evaluations, pipeline items, alerts and generated research reports.",
      "We do not collect payment card details in the application; if and when billing is enabled it is handled by a payment processor.",
    ],
  },
  {
    heading: "Workspaces are shared, not personal",
    body: [
      "MarginMap is organised around workspaces, not individual accounts. Every search, deal evaluation, watchlist, pipeline item, price alert, analyst report and activity-log entry you create belongs to the workspace you created it in, and is visible to every member of that workspace according to their role: owners and admins can manage everything, editors can create and change records, auditors have read-only access.",
      "This is enforced in the database with row-level security scoped to workspace membership, not to your user ID alone. If you do not want a record seen by your colleagues, do not create it in a shared workspace.",
      "Workspace owners and admins can invite and remove members. Removing a member revokes their access to the workspace but does not delete the records they created, because those records belong to the workspace.",
      "Owners and admins can also see an append-only activity log that records who performed which action, and when.",
    ],
  },
  {
    heading: "How your data is used",
    body: [
      "Workspace data is used to render your workspace and to compute the scores you request.",
      "We do not sell workspace data, do not share it with advertisers, and do not use your sourcing activity to build a public dataset.",
      "Catalog data — products, offers, completed sales and market snapshots — is shared platform data and is not derived from any individual workspace.",
    ],
  },
  {
    heading: "Where it is stored",
    body: [
      "The application runs on Lovable Cloud, which provides managed Postgres, authentication and server-side execution. Data is stored in that managed database with access restricted by row-level security.",
      "AI analyst reports are generated by sending computed figures and the associated catalog evidence rows to a model provider through the Lovable AI Gateway. The prompt contains your question, the selected product variant and the catalog evidence; it does not contain your name, email or account identifier. The resulting report is stored against your workspace and is therefore visible to other members of that workspace.",
    ],
  },

  {
    heading: "Retention and deletion",
    body: [
      "Workspace records persist until you delete them or delete your account. Deleting a watchlist, evaluation, pipeline item or alert removes the row.",
      "To request export or full deletion of your account and associated workspace data, use the contact form and select the security or privacy topic. We action deletion requests within 30 days.",
    ],
  },
  {
    heading: "Cookies and analytics",
    body: [
      "The application stores an authentication session in browser storage so you stay signed in, and a small preference value for your selected role mode. These are functional, not advertising, and there is no cross-site tracking.",
    ],
  },
  {
    heading: "Shared responsibility",
    body: [
      "The hosting platform provides infrastructure controls including managed authentication, transport encryption and database access control. MarginMap, as the application owner, is responsible for the schema, access policies, and how data is used inside the product.",
      "You are responsible for keeping your credentials secure and for the lawfulness of any data you enter into your workspace.",
      "This page describes current practice. It is not an audit, a certification, or a statement of compliance with any specific regulatory framework.",
    ],
  },
];

function PrivacyPage() {
  return (
    <>
      <PageHero
        kicker="Legal"
        title="Privacy"
        lede="This page is maintained by MarginMap to answer common privacy and data-handling questions about the product. It describes what the application actually does today."
      />

      <div className="mx-auto max-w-3xl px-4 py-14">
        <div className="space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="text-lg font-semibold tracking-tight">{s.heading}</h2>
              {s.body.map((p) => (
                <p
                  key={p.slice(0, 40)}
                  className="mt-3 text-sm leading-relaxed text-muted-foreground"
                >
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>

        <p className="mt-12 text-sm text-muted-foreground">
          Questions about any of the above?{" "}
          <Link to="/contact" className="text-primary underline">
            Contact us
          </Link>
          .
        </p>
      </div>
    </>
  );
}
