/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingCanonicalProductIdentityRouteImport } from './routes/_marketing.canonical-product-identity'
import { Route as MarketingConditionGradingRouteImport } from './routes/_marketing.condition-grading'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingEvidenceAndDataConfidenceRouteImport } from './routes/_marketing.evidence-and-data-confidence'
import { Route as MarketingFaqRouteImport } from './routes/_marketing.faq'
import { Route as MarketingLandedCostRouteImport } from './routes/_marketing.landed-cost'
import { Route as MarketingMarketplaceFeesRouteImport } from './routes/_marketing.marketplace-fees'
import { Route as MarketingMethodologyRouteImport } from './routes/_marketing.methodology'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing.privacy'
import { Route as MarketingResellerMarginAndRoiRouteImport } from './routes/_marketing.reseller-margin-and-roi'
import { Route as MarketingSoldCompsVsAskingPriceRouteImport } from './routes/_marketing.sold-comps-vs-asking-price'
import { Route as MarketingSourcingWorkflowRouteImport } from './routes/_marketing.sourcing-workflow'
import { Route as MarketingTermsRouteImport } from './routes/_marketing.terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppEvaluateRouteImport } from './routes/app.evaluate'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWatchlistsRouteImport } from './routes/app.watchlists'
import { Route as AppVariantIdRouteImport } from './routes/app.variant.$id'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCanonicalProductIdentityRoute =
  MarketingCanonicalProductIdentityRouteImport.update({
    id: '/canonical-product-identity',
    path: '/canonical-product-identity',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingConditionGradingRoute =
  MarketingConditionGradingRouteImport.update({
    id: '/condition-grading',
    path: '/condition-grading',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingEvidenceAndDataConfidenceRoute =
  MarketingEvidenceAndDataConfidenceRouteImport.update({
    id: '/evidence-and-data-confidence',
    path: '/evidence-and-data-confidence',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLandedCostRoute = MarketingLandedCostRouteImport.update({
  id: '/landed-cost',
  path: '/landed-cost',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingMarketplaceFeesRoute =
  MarketingMarketplaceFeesRouteImport.update({
    id: '/marketplace-fees',
    path: '/marketplace-fees',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingMethodologyRoute = MarketingMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingResellerMarginAndRoiRoute =
  MarketingResellerMarginAndRoiRouteImport.update({
    id: '/reseller-margin-and-roi',
    path: '/reseller-margin-and-roi',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingSoldCompsVsAskingPriceRoute =
  MarketingSoldCompsVsAskingPriceRouteImport.update({
    id: '/sold-comps-vs-asking-price',
    path: '/sold-comps-vs-asking-price',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingSourcingWorkflowRoute =
  MarketingSourcingWorkflowRouteImport.update({
    id: '/sourcing-workflow',
    path: '/sourcing-workflow',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluateRoute = AppEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistsRoute = AppWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => AppRoute,
} as any)
const AppVariantIdRoute = AppVariantIdRouteImport.update({
  id: '/variant/$id',
  path: '/variant/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof MarketingAboutRoute
  '/canonical-product-identity': typeof MarketingCanonicalProductIdentityRoute
  '/condition-grading': typeof MarketingConditionGradingRoute
  '/contact': typeof MarketingContactRoute
  '/evidence-and-data-confidence': typeof MarketingEvidenceAndDataConfidenceRoute
  '/faq': typeof MarketingFaqRoute
  '/landed-cost': typeof MarketingLandedCostRoute
  '/marketplace-fees': typeof MarketingMarketplaceFeesRoute
  '/methodology': typeof MarketingMethodologyRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/reseller-margin-and-roi': typeof MarketingResellerMarginAndRoiRoute
  '/sold-comps-vs-asking-price': typeof MarketingSoldCompsVsAskingPriceRoute
  '/sourcing-workflow': typeof MarketingSourcingWorkflowRoute
  '/terms': typeof MarketingTermsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/compare': typeof AppCompareRoute
  '/app/evaluate': typeof AppEvaluateRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlists': typeof AppWatchlistsRoute
  '/app/': typeof AppIndexRoute
  '/app/variant/$id': typeof AppVariantIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof MarketingAboutRoute
  '/canonical-product-identity': typeof MarketingCanonicalProductIdentityRoute
  '/condition-grading': typeof MarketingConditionGradingRoute
  '/contact': typeof MarketingContactRoute
  '/evidence-and-data-confidence': typeof MarketingEvidenceAndDataConfidenceRoute
  '/faq': typeof MarketingFaqRoute
  '/landed-cost': typeof MarketingLandedCostRoute
  '/marketplace-fees': typeof MarketingMarketplaceFeesRoute
  '/methodology': typeof MarketingMethodologyRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/reseller-margin-and-roi': typeof MarketingResellerMarginAndRoiRoute
  '/sold-comps-vs-asking-price': typeof MarketingSoldCompsVsAskingPriceRoute
  '/sourcing-workflow': typeof MarketingSourcingWorkflowRoute
  '/terms': typeof MarketingTermsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/compare': typeof AppCompareRoute
  '/app/evaluate': typeof AppEvaluateRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlists': typeof AppWatchlistsRoute
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/app/variant/$id': typeof AppVariantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/canonical-product-identity': typeof MarketingCanonicalProductIdentityRoute
  '/_marketing/condition-grading': typeof MarketingConditionGradingRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/evidence-and-data-confidence': typeof MarketingEvidenceAndDataConfidenceRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/landed-cost': typeof MarketingLandedCostRoute
  '/_marketing/marketplace-fees': typeof MarketingMarketplaceFeesRoute
  '/_marketing/methodology': typeof MarketingMethodologyRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/reseller-margin-and-roi': typeof MarketingResellerMarginAndRoiRoute
  '/_marketing/sold-comps-vs-asking-price': typeof MarketingSoldCompsVsAskingPriceRoute
  '/_marketing/sourcing-workflow': typeof MarketingSourcingWorkflowRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/compare': typeof AppCompareRoute
  '/app/evaluate': typeof AppEvaluateRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlists': typeof AppWatchlistsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/variant/$id': typeof AppVariantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/canonical-product-identity'
    | '/condition-grading'
    | '/contact'
    | '/evidence-and-data-confidence'
    | '/faq'
    | '/landed-cost'
    | '/marketplace-fees'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/reseller-margin-and-roi'
    | '/sold-comps-vs-asking-price'
    | '/sourcing-workflow'
    | '/terms'
    | '/app/alerts'
    | '/app/compare'
    | '/app/evaluate'
    | '/app/pipeline'
    | '/app/search'
    | '/app/settings'
    | '/app/watchlists'
    | '/app/'
    | '/app/variant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/canonical-product-identity'
    | '/condition-grading'
    | '/contact'
    | '/evidence-and-data-confidence'
    | '/faq'
    | '/landed-cost'
    | '/marketplace-fees'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/reseller-margin-and-roi'
    | '/sold-comps-vs-asking-price'
    | '/sourcing-workflow'
    | '/terms'
    | '/app/alerts'
    | '/app/compare'
    | '/app/evaluate'
    | '/app/pipeline'
    | '/app/search'
    | '/app/settings'
    | '/app/watchlists'
    | '/'
    | '/app'
    | '/app/variant/$id'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/auth'
    | '/_marketing/about'
    | '/_marketing/canonical-product-identity'
    | '/_marketing/condition-grading'
    | '/_marketing/contact'
    | '/_marketing/evidence-and-data-confidence'
    | '/_marketing/faq'
    | '/_marketing/landed-cost'
    | '/_marketing/marketplace-fees'
    | '/_marketing/methodology'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/_marketing/reseller-margin-and-roi'
    | '/_marketing/sold-comps-vs-asking-price'
    | '/_marketing/sourcing-workflow'
    | '/_marketing/terms'
    | '/app/alerts'
    | '/app/compare'
    | '/app/evaluate'
    | '/app/pipeline'
    | '/app/search'
    | '/app/settings'
    | '/app/watchlists'
    | '/_marketing/'
    | '/app/'
    | '/app/variant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/canonical-product-identity': {
      id: '/_marketing/canonical-product-identity'
      path: '/canonical-product-identity'
      fullPath: '/canonical-product-identity'
      preLoaderRoute: typeof MarketingCanonicalProductIdentityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/condition-grading': {
      id: '/_marketing/condition-grading'
      path: '/condition-grading'
      fullPath: '/condition-grading'
      preLoaderRoute: typeof MarketingConditionGradingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/evidence-and-data-confidence': {
      id: '/_marketing/evidence-and-data-confidence'
      path: '/evidence-and-data-confidence'
      fullPath: '/evidence-and-data-confidence'
      preLoaderRoute: typeof MarketingEvidenceAndDataConfidenceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/landed-cost': {
      id: '/_marketing/landed-cost'
      path: '/landed-cost'
      fullPath: '/landed-cost'
      preLoaderRoute: typeof MarketingLandedCostRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/marketplace-fees': {
      id: '/_marketing/marketplace-fees'
      path: '/marketplace-fees'
      fullPath: '/marketplace-fees'
      preLoaderRoute: typeof MarketingMarketplaceFeesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/methodology': {
      id: '/_marketing/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MarketingMethodologyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/reseller-margin-and-roi': {
      id: '/_marketing/reseller-margin-and-roi'
      path: '/reseller-margin-and-roi'
      fullPath: '/reseller-margin-and-roi'
      preLoaderRoute: typeof MarketingResellerMarginAndRoiRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/sold-comps-vs-asking-price': {
      id: '/_marketing/sold-comps-vs-asking-price'
      path: '/sold-comps-vs-asking-price'
      fullPath: '/sold-comps-vs-asking-price'
      preLoaderRoute: typeof MarketingSoldCompsVsAskingPriceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/sourcing-workflow': {
      id: '/_marketing/sourcing-workflow'
      path: '/sourcing-workflow'
      fullPath: '/sourcing-workflow'
      preLoaderRoute: typeof MarketingSourcingWorkflowRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluate': {
      id: '/app/evaluate'
      path: '/evaluate'
      fullPath: '/app/evaluate'
      preLoaderRoute: typeof AppEvaluateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlists': {
      id: '/app/watchlists'
      path: '/watchlists'
      fullPath: '/app/watchlists'
      preLoaderRoute: typeof AppWatchlistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/variant/$id': {
      id: '/app/variant/$id'
      path: '/variant/$id'
      fullPath: '/app/variant/$id'
      preLoaderRoute: typeof AppVariantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingCanonicalProductIdentityRoute: typeof MarketingCanonicalProductIdentityRoute
  MarketingConditionGradingRoute: typeof MarketingConditionGradingRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingEvidenceAndDataConfidenceRoute: typeof MarketingEvidenceAndDataConfidenceRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingLandedCostRoute: typeof MarketingLandedCostRoute
  MarketingMarketplaceFeesRoute: typeof MarketingMarketplaceFeesRoute
  MarketingMethodologyRoute: typeof MarketingMethodologyRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingResellerMarginAndRoiRoute: typeof MarketingResellerMarginAndRoiRoute
  MarketingSoldCompsVsAskingPriceRoute: typeof MarketingSoldCompsVsAskingPriceRoute
  MarketingSourcingWorkflowRoute: typeof MarketingSourcingWorkflowRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingCanonicalProductIdentityRoute:
    MarketingCanonicalProductIdentityRoute,
  MarketingConditionGradingRoute: MarketingConditionGradingRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingEvidenceAndDataConfidenceRoute:
    MarketingEvidenceAndDataConfidenceRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingLandedCostRoute: MarketingLandedCostRoute,
  MarketingMarketplaceFeesRoute: MarketingMarketplaceFeesRoute,
  MarketingMethodologyRoute: MarketingMethodologyRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingResellerMarginAndRoiRoute: MarketingResellerMarginAndRoiRoute,
  MarketingSoldCompsVsAskingPriceRoute: MarketingSoldCompsVsAskingPriceRoute,
  MarketingSourcingWorkflowRoute: MarketingSourcingWorkflowRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCompareRoute: typeof AppCompareRoute
  AppEvaluateRoute: typeof AppEvaluateRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistsRoute: typeof AppWatchlistsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVariantIdRoute: typeof AppVariantIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCompareRoute: AppCompareRoute,
  AppEvaluateRoute: AppEvaluateRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistsRoute: AppWatchlistsRoute,
  AppIndexRoute: AppIndexRoute,
  AppVariantIdRoute: AppVariantIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
