// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzmeepgamxldfsksaxmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bWVlcGdhbXhsZGZza3NheG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1NTIzNDQsImV4cCI6MjEwMTEyODM0NH0.pooLLrsEJg0tjCBfJQ4uMiZqpE1QeGg8h7xWSL7EU50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});